### ISSUE TITLE
通过 RPPI 安装方案，自定义的 opencc 文件没有下载

### ISSUE THREAD

**Issue by amorphobia** [LibreService/micro_plum#2]
https://github.com/amorphobia/rime-jiandao/tree/release/opencc

这个目录下面的 [s2tg.json](https://github.com/amorphobia/rime-jiandao/blob/release/opencc/s2tg.json), [STGPhrases.ocd2](https://github.com/amorphobia/rime-jiandao/blob/release/opencc/STGPhrases.ocd2), 和 [STGCharacters.ocd2](https://github.com/amorphobia/rime-jiandao/blob/release/opencc/STGCharacters.ocd2) 没能成功下载，报 404 错误。

**Comment by eagleoflqj** [comment]
Fixed at https://github.com/LibreService/micro_plum/commit/6ca69ba9fea93aa51dfc26792a58dd5443c781a5
