### ISSUE TITLE
`symbols.yaml`没有用了

### ISSUE THREAD

**Issue by bczhc** [LibreService/micro_plum#3]
如题，plum仓库的[`symbols.yaml`](https://github.com/bczhc/rime-config/blob/ac3aef615cdb74fe1407ecf566c86afa5e3bac2c/symbols.yaml#L57)文件配置了符号直出，可部署之后的应用依然用着默认的符号方案。

**Comment by eagleoflqj** [comment]
Fixed at https://github.com/LibreService/micro_plum/commit/7aba0e219a1e615e1a4e0a6acc771d20fb3353f2
